name: CombatLog
version: ${version}
description: ${description}
author: iiSnipez
contributors:
  - JackProehl
website: https://github.com/MacMoment/CombatLog
main: me.iiSnipez.CombatLog.CombatLog
api-version: "1.21"
load: STARTUP
folia-supported: false

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  combatlog.reload:
    description: Allows one to reload the configuration file's options.
    default: op
  combatlog.update:
    description: Allows one to see UpdateChecks upon logging in.
    default: op
  combatlog.bypass:
    description: Allows one to bypass all of CombatLog's log prevention methods.
    default: false
